Migration/urls.py
from django.contrib import admin
from django.urls import path,include
from django_telethon.urls import django_telethon_urls

admin.autodiscover()
from django.conf.urls.static import static
from django.conf import settings


#
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('home/',include('my_site.urls',namespace='my_site')),
#     path('telegram/', django_telethon_urls()),
# ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('my_site.urls',namespace='my_site')),
    path('telegram/', django_telethon_urls()),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/urls.py
from django.conf.urls.static import static
from django.urls import path

from Migration import settings
from . import views
app_name = 'my_site'

urlpatterns=[
    path('home/',views.home, name='home'),
    path('work/', views.work, name='work'),
    path('study/',views.study,name='study'),
    path('life/', views.life, name='life'),
    path('consulting/',views.consulting, name='consulting'),
    path('signin/', views.signin, name='signin'),
    path('login/', views.view_login, name='login'),
    path('vissa/', views.vissa, name='vissa'),
    path('usa/', views.usa, name='usa'),
    path('germany/', views.germany, name='germany'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('look_profile/', views.look_profile, name='look_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('suggestion/', views.suggestion, name='suggestion'),
    path('Verification_code/', views.Verification_code_view, name='Verification_code'),
    path('iamge/', views.upload_photo, name='upload_photo'),
    path('reset-password/', views.reset_password_view, name='reset_password'),
    # path('iamge/', views.model_form_upload, name='upload_photo'),

]

my_site/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render, reverse


class signin_model(models.Model):
    user_name = models.CharField(max_length=20)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    mobile = models.CharField(max_length=11)
    users = models.OneToOneField(User, on_delete=models.CASCADE, related_name='account')
    photo = models.ImageField(upload_to='photos/')

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class UserProfile(models.Model):
    photo = models.ImageField(upload_to='photos/')


# class Document(models.Model):
#     # document_addr = models.FileField(upload_to='documents/')
#     # uploaded_at = models.DateTimeField(auto_now_add=True)
#     document_addr = models.FileField(upload_to='documents/%Y/%m/%d/')

my_site/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth.models import User
from .models import signin_model
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from datetime import date, datetime
from khayyam import JalaliDate, JalaliDatetime, TehranTimezone
import csv
from datetime import date
import random

save_user = False
form_image=False

def home(request):

    return render(request, 'Migration/post/home.html', {'save_user': save_user,'form_image':form_image})


def work(request):
    return render(request, 'Migration/post/work.html', {'save_user': save_user,'form_image':form_image})


def study(request):
    return render(request, 'Migration/post/study.html', {'save_user': save_user,'form_image':form_image})


def life(request):
    return render(request, 'Migration/post/life.html', {'save_user': save_user,'form_image': form_image})


def vissa(request):
    return render(request, 'Migration/post/vissa.html', {'save_user': save_user,'form_image': form_image})


def usa(request):
    return render(request, 'Migration/post/countries/usa.html', {'save_user': save_user,'form_image': form_image})


def germany(request):
    return render(request, 'Migration/post/countries/germany.html', {'save_user': save_user,'form_image': form_image})


def about(request):

    return render(request, 'Migration/post/about.html', {'save_user': save_user,'form_image': form_image})


def feedback(request):
    sent = False
    if request.method == "POST":
        form = feedback_form(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = cd['name']
            emails = cd['email']
            subject = cd['subject']
            message = cd['message']
            phone = cd['phone']
            msg = "name:{0}\nphone:{1}\nemail:{2}\nmessage:\n{3}".format(name, phone, emails, message)
            send_mail(subject, msg, 'lopmotop@gmail.com', ['lopmotop@gmail.com'], fail_silently=False)
            sent = True
    else:
        form = feedback_form()

    return render(request, 'Migration/post/feedback.html', {'save_user': save_user, 'forms': form,'form_image': form_image})


def consulting(request):
    if not save_user:
        return redirect("my_site:signin")
    print('consulting')

    my_range = range(1, 100)
    context = {
        'my_range': my_range
    }

    sent = False
    if request.method == "POST":
        print('e-post')
        form = email_consulting(request.POST)
        if form.is_valid():
            print('e-valid')

            cd = form.cleaned_data
            name = cd['name']
            type_consulting = cd['type_consulting']
            level_school = cd['level_school']
            type = cd['type']
            age = cd['age']
            type_price = cd['type_price']
            mobile = cd['mobile']
            city = cd['city']

            msg = ("name: {0}\nphone: {1}\ncity: {2}\ntype_consulting: {3}"
                   "\nlevel_school: {4}\ntype: {5}"
                   "\ntype_price: {6}\nage {7}").format(
                name, mobile, city, type_consulting, level_school, type, type_price, age)

            send_mail("فرم مشاوره", msg, 'lopmotop@gmail.com',
                      ['lopmotop@gmail.com'], fail_silently=False)
            sent = True
    else:
        print('e-get')

    form = email_consulting()
    return render(request, 'Migration/post/consulting.html',
                  {'save_user': save_user, 'sent': sent, "context": context,'form_image': form_image})


# send_code = 0

code = 0


def Verification_code_view(request):
    # global code
    # import random
    # code = random.randint(100000, 999999)
    # print(code)
    # global send_code
    # import random
    # code = random.randint(100000, 999999)
    # print(code)
    # form=signin_form(request.POST)
    # if form.is_valid():
    #     email=form.cleaned_data['email']
    #     print(email)
    # send_code = True
    # return redirect('my_site:signin')
    return render(request, 'Migration/forms/signin.html')


def signin(request):
    # return render(request,'Migration/post/home.html')
    print('yes')
    global code
    global save_user
    if not save_user:
        print('NO save')
        # user = request.user
        # try:
        #     account = signin_model.objects.get(users=user)
        #
        # except:
        #
        if request.method == "POST":
            form = signin_form(request.POST)
            print('post')
            if form.is_valid():
                print('valid-post')
                cd = form.cleaned_data
                if cd['repassword'] == cd["password"]:

                    if cd['code'] == '':
                        print('shet')
                        import random
                        code = random.randint(100000, 999999)
                        print(code)
                        dict_form= [cd['user_name'], cd['first_name'], cd['last_name'], cd['password'], cd['repassword'],
                                    cd['email'], cd['mobile']]

                        send_mail('کد تایید', 'کد تایید شما برای ثبت نام در سایت مهاجر\n' + str(code),
                                  'lopmotop@gmail.com',
                                  [cd['email']],
                                  fail_silently=False)

                        return render(request,'Migration/forms/signin.html',{'form':form,'dict_form':dict_form})
                    else:
                        print("code", code)
                        if str(code) == str(cd['code']):

                            user = User.objects.create_user(cd["user_name"], cd["email"], cd["password"])
                            user.first_name = cd["first_name"]
                            user.last_name = cd["last_name"]
                            account = signin_model.objects.create(users=user)
                            user.first_name = cd['first_name']
                            user.last_name = cd['last_name']
                            account.first_name = cd['first_name']
                            account.last_name = cd['last_name']
                            account.password = cd['password']
                            account.email = cd['email']
                            account.mobile = cd['mobile']
                            account.user_name = cd['user_name']
                            user.save()
                            account.save()
                            save_user = True
                            user = authenticate(request, username=cd["user_name"], password=cd["password"])
                            if user is not None:
                                login(request, user)
                                messages.success(request, "خوش اومدی")  # ایجاد پیام موفقیت
                                return render(request, 'Migration/post/home.html',{'save_user': save_user, 'forms': form,'form_image': form_image})
                        else:
                            messages.error(request, "کد تایید نادرست است")  # ایجاد پیام موفقیت
                            return render(request, 'Migration/post/home.html', {'save_user': save_user, 'forms': form,'form_image': form_image})

#                         # if cd['code'] != '':
#                         #     print('shet')
#                         #     if str(code) == str(cd['code']):
#                         #         print('shetttt')


#
#
#                         # return render(request, 'Migration/forms/signin.html',
#                         #               {'save_user': save_user, 'forms': form, 'account': account})

                    # if str(code)==str(cd['code']):
                    #     user.save()
                    #     account.save()
                    #     save_user = True
                    #     user = authenticate(request, username=cd["user_name"], password=cd["password"])
                    #
                    #     if user is not None:
                    #         login(request, user)
                    #
                    #     return render(request, 'Migration/forms/signin.html', {'save_user': save_user, 'forms': form})
                    # else:
                    #     messages.error(request, "کد تایید نادرست است")  # ایجاد پیام موفقیت
                    #     return render(request, 'Migration/post/home.html', {'save_user': save_user, 'forms': form})

                else:
                    not_correct_password = True
                    return render(request, 'Migration/forms/signin.html',
                    {'save_user': save_user, "not_correct_password": not_correct_password, 'forms': form,'form_image': form_image})
                # else:
                #     return render(request, 'Migration/forms/signin.html', {"forms": form})
            else:
                return render(request, 'Migration/forms/signin.html', {"forms": form,'form_image': form_image})

        else:
            # global send_code
            # if send_code:
            #     import random
            #     code = random.randint(100000, 999999)
            #
            form = signin_form()
            print("get")
            return render(request, 'Migration/forms/signin.html', {"forms": form,'form_image': form_image})
    else:
        return redirect("my_site:consulting")


def view_login(request):
    print('log-')
    global save_user,form_image
    if request.method == "POST":
        form = login_form(request.POST)
        if form.is_valid():
            print('log-valid')
            cd = form.cleaned_data
            # from django.db.models import Q
            #
            # if signin_model.objects.filter(Q(user_name=cd['user_name']) & Q(password=cd['password'])).exists():
            #     print('open')
            user = authenticate(request, username=cd["user_name"], password=cd["password"])

my_site/templates/Migration/post/about.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <div style="text-align: right">
        <div>

<section style="margin-top:90px" class="home-consulting consulting-blog">
                <div class="row">
                    <div class="col-12">
                        <div class="g2-call">
                          <div class="g2-call__right">
                              <h2>برای مهاجرت نیاز به مشاوره داری؟</h2>
                              <p>همین حالا فرم درخواست رزرو مشاوره رو پر کن تا برای مهاجرت مشکلی نداشته باشی</p>
                          </div>
                          <div class="g2-call__left">
                              <a href="{% url 'my_site:consulting' %}" class="button_Counseling">درخواست فرم مشاوره</a>
                          </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>
        <br><br><br>
        <div>
        <h4 style="text-align: center"> چرا مهاجر...؟!</h4>
            <br><br>
            <div>
                <div class="about-second-div">
                    <h5 class="about-second-div-h5" >سابقه درخشان</h5>
                    <br>
                    <p>موسسه مهاجر با 14 سال سابقه فعالیت در زمینه مهاجرت و دارای بیش از هزار پرونده موفق در سال</p>
                </div>
                <div class="about-second-div">
                    <h5 class="about-second-div-h5">مشاوره دقیق</h5>
                    <br>
                    <p>امکان دریافت مشاوره مهاجرتی از متخصصین این زمینه که خود سابقه مهاجرت و زندگی در اکثر کشورهای جهان را دارند</p>
                </div>
                <div class="about-second-div">
                    <h5 class="about-second-div-h5">همراهی شما</h5>
                    <br>
                    <p>همراهی علاقمندان و متقاضیان امور مهاجرت با خانواده مهاجر در تمامی پلتفرم های مجازی و حقیقی</p>
                </div>
            </div>
        </div>
        <div>
            <a class="button_Counseling_suggestions about-thirty-div-button"  href="{% url 'my_site:home' %}" style="margin-right: 10%">مشاوره: 1111 248 01+ </a>
            <a class="button_Counseling_suggestions about-thirty-div-button"  href="{% url 'my_site:home' %}">رزرو مشاوره مهاجرتی </a>
            <a class="button_Counseling_suggestions about-thirty-div-button"  href="{% url 'my_site:consulting' %}">درخواست فرم مشاوره </a>

        </div>
<section style="margin-top:90px" class="home-consulting consulting-blog">
                <div class="row">
                    <div class="col-12">
                        <div class="g2-call" style="background-color: #f39c12">
                          <div class="g2-call__right">
                              <h2>نظرات و پیشنهاداتتو با ما درمیون بزار</h2>
{#                              <p>همین حالا فرم درخواست رزرو مشاوره رو پر کن تا برای مهاجرت مشکلی نداشته باشی</p>#}
                          </div>
                          <div class="g2-call__left">
                              <a href="{% url 'my_site:feedback' %}" class="button_Counseling" style="margin-top: 0;
                                        background-color:#31414a ">بزن روش</a>
                          </div>
                        </div>
                    </div>
                </div>
            </section>
<br><br><br>
        <div>

        <h4>درباره مهاجر</h4>
            <br>
            <p>مهاجرت، خرید ملک، ثبت شرکت، سفر و تحصیل در خارج از کشور، موضوعاتی هستند که این روزها به شنیدنشان عادت کرده‌ایم. خانواده بزرگ گو تو تی آر در کنار شماست تا این مسیر برایتان آسان شود. هدف تیم، ارائه اطلاعات دقیق و مشاوره کامل، هم راستا با شرایط و رزومه شما و ترسیم بهترین مسیر مهاجرتی پیش رویتان است که در ادامه این مسیر با ارائه خدمات کامل، تمام مراحل اخذ پذیرش تحصیلی، کاری و همچنین فرایند خرید ملک، ثبت شرکت و … انجام داده و آینده‌ای مطلوب و باب میل شما برایتان به ارمغان می‌آورد. گو تو تی آر متشکل از ۲۰۰ نفر است که در زمینه مهاجرت به تمامی کشور های پرطرفدار دنیا در تمامی زمینه‌های مهاجرتی اعم از تحصیلی، خرید ملک و ثبت شرکت آماده ارائه خدمات هستند و در حال حاضر در پنج شهر داخل کشور و در چهار شعبه خارج از کشور مستقر می‌باشد.</p>
        </div>
        <div>

        </div>
    </div>
{% endblock %}

my_site/templates/Migration/post/feedback.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/vissa.css' %}">

{% endblock %}

{% block content %}

    <p>
    {% if sent %}
    پیام شما ثبت شد.با تشکر
    {% endif %}
    </p>
    <form method="post" style="text-align: right">
    {% csrf_token %}
        <label>نام:
            <input type="text" name="name" class="feedback-input">
        </label>
        <br><br>
        <label>ایمیل:
            <input type="email" name="email" class="feedback-input">
        </label>
        <br><br>
        <label>شماره موبایل:
            <input type="text" name="phone" class="feedback-input">
        </label>
        <br><br>
        <label>موضوع:
            <select name="subject" required class="feedback-input">
                <option value="شکایات">شکایات</option>
                <option value="انتقادات و پیشنهادات">انتقادات و پیشنهادات</option>

            </select>
        </label>
        <br><br>
        <label>پیام:
            <input type="text" name="message" class="feedback-input">
        </label>
        <br><br>
    <input type="submit" value="ثبت پیام" class="feedback-input">
    </form>

        <br><br>
<div style="direction: rtl">
    {% if forms.errors %}
            لطفا خطاهای زیر را اصلاح کنید:
        <br> <br>
        {% for field in forms %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ field.label }}: {{ error }}
                    <br>
                {% endfor %}
            {% endif %}
        {% endfor %}

        {% if forms.non_field_errors %}
            {{ forms.non_field_errors }}
            <br>
    {% endif %}

    {% endif %}
</div>
{% endblock %}

my_site/templates/Migration/post/home.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">{% endblock %}

{% block content %}
        <div class="first">
        <div class="first_child">
            <video controls class="video-home" ><source src="{% static 'video/tablig-go2tr.mp4' %}" type="video/mp4"></video>
        </div>
        <div class="first_child first_child_text">
            <h2>مهاجرتت با ما</h2>
            <h5>شرکت مهاجر، مرجع اطلاعات مهاجرتی و خدمات مشاوره آنلاین و روش های مختلف مهاجرت، با خدمات رسانی در تمام روز در ایران</h5>
            <a href="{% url 'my_site:study' %}" class="button">تحصیل در خارج</a>
            <a href="{% url 'my_site:about' %}" class="button_about">ارتباط با ما</a>

        </div>

    </div>
    <div>
        <h2 id="works">خدمات شرکت مهاجر</h2>
        <div class="works_parent">
            <div class="works_child">

                <h3>تحصیل در خارج</h3>
                <p>شرایط شرکت در آزمون ها، رشته ها و دانشگاه های معتبر خارج را در این بخش مطالعه کنید.</p>
                        <div>
                            <br><br>
                    <a href="#" class="button">تحصیل در کانادا</a>
                    <a href="#" class="button">تحصیل در آلمان</a>
                    <a href="#" class="button">تحصیل در ژاپن</a>
                    <a href="#" class="button">تحصیل در فرانسه</a>
                </div>
            </div>
            <div class="works_child">

                <h3> خرید ملک/ثبت شرکت در خارج</h3>
                <p>با شرایط ثبت شرکت و یا خرید/اجاره ملک در خارج از کشور آشنا شوید. چه شرایطی در این مسیر وجود دارد؟</p>
                <div>
                    <a href="#" class="button">ملک در انگلیس</a>
                    <a href="#" class="button">ملک در کانادا</a>
                    <a href="#" class="button">ملک در کره جنوبی</a>
                    <a href="#" class="button">ملک در فرانسه</a>
                </div>
            </div>

            <div class="works_child">
                <h3>کار در خارج</h3>
                <p>با شرایط کار در خارج، انواع ویزاهای کاری و مشاغل مورد‌نیاز کشورها در این بخش آشنا شوید</p>
                <div>
                    <a href="#" class="button">کار در کانادا</a>
                    <a href="#" class="button">کار در آلمان</a>
                    <a href="#" class="button">کار در ژاپن</a>
                    <a href="#" class="button">کار در فرانسه</a>
                </div>
            </div>

                <div class="works_child">
                    <h3>سفر تفریحی به خارج</h3>
                    <p>اگه حوصلت سررفته و دنبال یه سفر جذاب و هیجان انگیز هستی حتما این بخشو ببین</p>
                    <div>
                        <a href="#" class="button">سفر به آمریکا</a>
                        <a href="#" class="button">سفر به آلمان</a>
                        <a href="#" class="button">سفر به اسپانیا</a>
                        <a href="#" class="button">سفر به فرانسه</a>
                    </div>
                </div>
        </div>

    </div>

<section style="margin-top:90px" class="home-consulting consulting-blog">
                <div class="row">
                    <div class="col-12">
                        <div class="g2-call">
                          <div class="g2-call__right">
                              <h2>برای مهاجرت نیاز به مشاوره داری؟</h2>
                              <p>همین حالا فرم درخواست رزرو مشاوره رو پر کن تا برای مهاجرت مشکلی نداشته باشی</p>
                          </div>
                          <div class="g2-call__left">
                              <a href="{% url 'my_site:consulting' %}" class="button_Counseling">درخواست فرم مشاوره</a>
                          </div>
                        </div>
                    </div>
                </div>
            </section>


                          <div class="g2-call-news">
                          <div class="g2-call__right">
                              <h3 style="text-align: center;padding-bottom: 20px;color:#f39c12 ">اخبار</h3>
                              <a href="#" class="news">

                              <h5>چندین خانواده افریقایی الاصل از خاک کشور آلمان اخراج شدند</h5>

                              </a>
                              <a href="#" class="news">

                              <h5>مجلس انگلستان با طرح ویرایش قوانین پذیرش مهاجرین مخالفت کرد</h5>
                              </a><a href="#" class="news">

                              <h5>دولت کانادا اعلام کرد امسال 10000 مهاجر تابعیت این کشور را دریافت کردند</h5>
                              </a>
                              </div>

                                  <div class="g2-call__left">
{#                              <a href="#" class="button_Counseling_news">پیشنهادات و انتقادات</a>#}
{#                          </div>#}
                        </div>
            </div>


            <div class="suggestions_news">
                        <div class="g2-call-suggestions">
                          <div class="g2-call__right">
                              <h5>اگه پیشنهادی،تجربه ای یا انتقادی داری باهامون درمیون بزار </h5>
                              </div>
                          <div class="g2-call__left">
                              <a href="{% url 'my_site:suggestion' %}" class="button_Counseling_suggestions">پیشنهادات و انتقادات</a>
                          </div>
                        </div>


    </div>
<script>
    setInterval(function(){
        const headings = document.querySelectorAll('.g2-call-news .g2-call__right a');
        const lastHeading = headings[headings.length - 1];
        lastHeading.parentNode.insertBefore(lastHeading, headings[0]);
    }, 5000); // هر 3 ثانیه یکبار
</script>

{% endblock %}

my_site/templates/Migration/post/look_profile.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
        <link rel="stylesheet" type="text/css" href="{% static "css/home.css" %}" >
{% endblock %}
{% block content %}
    <div>
    :user name<p>{{account.user_name}}</p>
    :name<p>{{account.first_name}}{{ account.last_name }}</p>
    :email<p>{{account.email}}</p>
    :mobile<p>{{account.mobile}}</p>

    </div>
{% endblock %}

my_site/templates/Migration/post/profile.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
        <link rel="stylesheet" type="text/css" href="{% static "css/home.css" %}" >
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block content %}
    <div style="text-align: right">
        <div>
            <div class="profile-first-div">
                <ul>
                    <li class="profile-first-div-ul-li">
                        <a href="{% url 'my_site:look_profile' %}">
                            <i style="font-size:24px" class="fa">&#xf08b;</i>
                            مشاهده پروفایل
                        </a>
                    </li>
                    <li class="profile-first-div-ul-li">
                        <a href="{% url 'my_site:edit_profile' %}">
                            <i style="font-size:24px" class="fa">&#xf044;</i>
                            ویرایش پروفایل
                        </a>

                    </li>
                    <li class="profile-first-div-ul-li">
                        <a href="#">
                            <i style="font-size:24px;padding: 0 50px" class="fa">&#xf1cd;</i>
                            پشتیبانی
                        </a>

                    </li>
                    <li class="profile-first-div-ul-li">
                        <a href="{% url 'my_site:upload_photo' %}">
                            <i style="font-size:24px;padding: 0 50px" class="fa fa-user user"></i>
                            عکس پروفایل
                        </a>

                    </li>
                    <li class="profile-first-div-ul-li">
                        <a href="#">
                            <i style="font-size:24px" class="fa">&#xf02e;</i>
                            دوره های نشان گذاری شده
                        </a>

                    </li>
                    <li class="profile-first-div-ul-li">
                        <a href="#">
                            <i style="font-size:24px" class="fa">&#xf219;</i>
                            دوره های خریداری شده
                        </a>

                    </li>
                    <li class="profile-first-div-ul-li">
                        <a href="{% url 'my_site:logout' %}">
                            <i style="font-size:24px;padding: 0 50px" class="fa" >&#xf08b;</i>
                            خروج
                        </a>

                    </li>
                </ul>
            </div>
        </div>
        <div>

        </div>
        <div>

        </div>
        <div>

        </div>
<br><br><br>
    </div>
{% endblock %}

my_site/templates/Migration/post/vissa.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/vissa.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <div style="text-align: right">
        <div style="text-align: right">
            <h1 class="visa-h1">اخذ ویزای کشورها</h1>
            <p class="visa-p">اخذ ویزای کشورها، اخذ یک مجوز رسمی است که اجازه می‌دهد تا شخص به طور قانونی وارد کشور خارجی شود. ویزا معمولا در گذرنامه، مهر می‌شود. انواع مختلفی برای ویزاها وجود دارد که هرکدام در کشور میزبان دارای حقوق و شرایط متفاوتی هستند و مدارکی که برای دریافت آن‌ها باید ارائه کنید، متفاوت است. در این مقاله به توضیح درباره ویزاها می‌پردازیم.</p>
            <h1 class="visa-h1"> ویزا چیست؟</h1>
            <p class="visa-p">ویزا یا روادید، برای ورود قانونی افراد به کشور دیگر است که مدت اقامت و زمان ورود و خروج، توسط سفارت یا کنسولگری و یا اداره مهاجرت، در ویزا مشخص می‌گردد و باعث می‌شود که فرد امکان تخطی از قانون کشور مبدا یا مقصد و انجام کارهای خلاف و مجرمانه یا آسیب‌زننده را نداشته باشد.</p>
            <b style="margin: 20px 15%;display: inline-block">ویزاها در انواع گوناگونی ارائه می‌شوند که شرایط اخذ و مدارک و هزینه‌شان بسته به هدف شما و نظر افسر سفارت متفاوت است.</b>
            <p class="visa-p">ویزاهای سنتی را می‌توان با تمبر در گذرنامه چسباند. اگر ویزاهای شما در گذرنامه شما چسبیده باشد، معمولاً دارای اطلاعاتی بر روی آن است که شامل نام، شماره گذرنامه، محل تولد، دلیل سفر و تاریخ انقضا است. ویزاهایی که با تمبر هستند، معمولاً اطلاعات کمتری در مورد شما ثبت کرده‌اند.</p>
            <div class="visa-div">ویزای برخی کشورها به دلیل عدم وجود سفارت در کشور مبدا، به صورت الکترونیکی هم صادر می شوند؛ مثل، ویزای استرالیا در ایران.</div>
            <p class="visa-p">ویزاها انواع مختلفی دارند. می‌توانند دانشجویی و تحصیلی، کار و کاریابی، سرمایه‌گذاری (مثل ثبت شرکت و خرید ملک)، ازدواج یا تولد و انواع دیگر باشند. در این بخش به معرفی انواع ویزاها خواهیم پرداخت.</p>
        </div>


        <img src="{% static 'images/types-of-visa.jpg' %}" alt="types-of-visa" class="types_of_visa">


                <div class="visa_child">
                    <div>
                        <a href="{% url 'my_site:usa' %}" class="button">ویزای آمریکا</a>
                        <a href="{% url 'my_site:germany' %}" class="button">ویزای آلمان</a>
                        <a href="#" class="button">ویزای اسپانیا</a>
                        <a href="#" class="button">ویزای فرانسه</a>
                        <a href="#" class="button">ویزای کانادا</a>
                        <a href="#" class="button">ویزای انگلیس</a>
                        <a href="#" class="button">ویزای ترکیه</a>
                        <a href="#" class="button">ویزای استرالیا</a>
                        <a href="#" class="button">ویزای روسیه</a>
                        <a href="#" class="button">ویزای چین</a>

                    </div>
                </div>
    </div>
{% endblock %}