Migration/urls.py
from django.contrib import admin
from django.urls import path,include
from django_telethon.urls import django_telethon_urls

admin.autodiscover()
from django.conf.urls.static import static
from django.conf import settings


#
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('home/',include('my_site.urls',namespace='my_site')),
#     path('telegram/', django_telethon_urls()),
# ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('my_site.urls',namespace='my_site')),
    path('telegram/', django_telethon_urls()),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/urls.py
from django.conf.urls.static import static
from django.urls import path

from Migration import settings
from . import views
app_name = 'my_site'

urlpatterns=[
    path('home/',views.home, name='home'),
    path('work/', views.work, name='work'),
    path('study/',views.study,name='study'),
    path('life/', views.life, name='life'),
    path('consulting/',views.consulting, name='consulting'),
    path('signin/', views.signin, name='signin'),
    path('login/', views.view_login, name='login'),
    path('vissa/', views.vissa, name='vissa'),
    path('usa/', views.usa, name='usa'),
    path('germany/', views.germany, name='germany'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('look_profile/', views.look_profile, name='look_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('suggestion/', views.suggestion, name='suggestion'),
    path('Verification_code/', views.Verification_code_view, name='Verification_code'),
    path('iamge/', views.upload_photo, name='upload_photo'),
    path('reset-password/', views.reset_password_view, name='reset_password'),
    # path('iamge/', views.model_form_upload, name='upload_photo'),

]

my_site/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render, reverse


class signin_model(models.Model):
    user_name = models.CharField(max_length=20)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    mobile = models.CharField(max_length=11)
    users = models.OneToOneField(User, on_delete=models.CASCADE, related_name='account')
    photo = models.ImageField(upload_to='photos/')

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class UserProfile(models.Model):
    photo = models.ImageField(upload_to='photos/')


# class Document(models.Model):
#     # document_addr = models.FileField(upload_to='documents/')
#     # uploaded_at = models.DateTimeField(auto_now_add=True)
#     document_addr = models.FileField(upload_to='documents/%Y/%m/%d/')

my_site/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth.models import User
from .models import signin_model
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from datetime import date, datetime
from khayyam import JalaliDate, JalaliDatetime, TehranTimezone
import csv
from datetime import date
import random

save_user = False
form_image=False

def home(request):

    return render(request, 'Migration/post/home.html', {'save_user': save_user,'form_image':form_image})


def work(request):
    return render(request, 'Migration/post/work.html', {'save_user': save_user,'form_image':form_image})


def study(request):
    return render(request, 'Migration/post/study.html', {'save_user': save_user,'form_image':form_image})


def life(request):
    return render(request, 'Migration/post/life.html', {'save_user': save_user,'form_image': form_image})


def vissa(request):
    return render(request, 'Migration/post/vissa.html', {'save_user': save_user,'form_image': form_image})


def usa(request):
    return render(request, 'Migration/post/countries/usa.html', {'save_user': save_user,'form_image': form_image})


def germany(request):
    return render(request, 'Migration/post/countries/germany.html', {'save_user': save_user,'form_image': form_image})


def about(request):

    return render(request, 'Migration/post/about.html', {'save_user': save_user,'form_image': form_image})


def feedback(request):
    sent = False
    if request.method == "POST":
        form = feedback_form(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = cd['name']
            emails = cd['email']
            subject = cd['subject']
            message = cd['message']
            phone = cd['phone']
            msg = "name:{0}\nphone:{1}\nemail:{2}\nmessage:\n{3}".format(name, phone, emails, message)
            send_mail(subject, msg, 'lopmotop@gmail.com', ['lopmotop@gmail.com'], fail_silently=False)
            sent = True
    else:
        form = feedback_form()

    return render(request, 'Migration/post/feedback.html', {'save_user': save_user, 'forms': form,'form_image': form_image})


def consulting(request):
    if not save_user:
        return redirect("my_site:signin")
    print('consulting')

    my_range = range(1, 100)
    context = {
        'my_range': my_range
    }

    sent = False
    if request.method == "POST":
        print('e-post')
        form = email_consulting(request.POST)
        if form.is_valid():
            print('e-valid')

            cd = form.cleaned_data
            name = cd['name']
            type_consulting = cd['type_consulting']
            level_school = cd['level_school']
            type = cd['type']
            age = cd['age']
            type_price = cd['type_price']
            mobile = cd['mobile']
            city = cd['city']

            msg = ("name: {0}\nphone: {1}\ncity: {2}\ntype_consulting: {3}"
                   "\nlevel_school: {4}\ntype: {5}"
                   "\ntype_price: {6}\nage {7}").format(
                name, mobile, city, type_consulting, level_school, type, type_price, age)

            send_mail("فرم مشاوره", msg, 'lopmotop@gmail.com',
                      ['lopmotop@gmail.com'], fail_silently=False)
            sent = True
    else:
        print('e-get')

    form = email_consulting()
    return render(request, 'Migration/post/consulting.html',
                  {'save_user': save_user, 'sent': sent, "context": context,'form_image': form_image})


# send_code = 0

code = 0


def Verification_code_view(request):
    # global code
    # import random
    # code = random.randint(100000, 999999)
    # print(code)
    # global send_code
    # import random
    # code = random.randint(100000, 999999)
    # print(code)
    # form=signin_form(request.POST)
    # if form.is_valid():
    #     email=form.cleaned_data['email']
    #     print(email)
    # send_code = True
    # return redirect('my_site:signin')
    return render(request, 'Migration/forms/signin.html')


def signin(request):
    # return render(request,'Migration/post/home.html')
    print('yes')
    global code
    global save_user
    if not save_user:
        print('NO save')
        # user = request.user
        # try:
        #     account = signin_model.objects.get(users=user)
        #
        # except:
        #
        if request.method == "POST":
            form = signin_form(request.POST)
            print('post')
            if form.is_valid():
                print('valid-post')
                cd = form.cleaned_data
                if cd['repassword'] == cd["password"]:

                    if cd['code'] == '':
                        print('shet')
                        import random
                        code = random.randint(100000, 999999)
                        print(code)
                        dict_form= [cd['user_name'], cd['first_name'], cd['last_name'], cd['password'], cd['repassword'],
                                    cd['email'], cd['mobile']]

                        send_mail('کد تایید', 'کد تایید شما برای ثبت نام در سایت مهاجر\n' + str(code),
                                  'lopmotop@gmail.com',
                                  [cd['email']],
                                  fail_silently=False)

                        return render(request,'Migration/forms/signin.html',{'form':form,'dict_form':dict_form})
                    else:
                        print("code", code)
                        if str(code) == str(cd['code']):

                            user = User.objects.create_user(cd["user_name"], cd["email"], cd["password"])
                            user.first_name = cd["first_name"]
                            user.last_name = cd["last_name"]
                            account = signin_model.objects.create(users=user)
                            user.first_name = cd['first_name']
                            user.last_name = cd['last_name']
                            account.first_name = cd['first_name']
                            account.last_name = cd['last_name']
                            account.password = cd['password']
                            account.email = cd['email']
                            account.mobile = cd['mobile']
                            account.user_name = cd['user_name']
                            user.save()
                            account.save()
                            save_user = True
                            user = authenticate(request, username=cd["user_name"], password=cd["password"])
                            if user is not None:
                                login(request, user)
                                messages.success(request, "خوش اومدی")  # ایجاد پیام موفقیت
                                return render(request, 'Migration/post/home.html',{'save_user': save_user, 'forms': form,'form_image': form_image})
                        else:
                            messages.error(request, "کد تایید نادرست است")  # ایجاد پیام موفقیت
                            return render(request, 'Migration/post/home.html', {'save_user': save_user, 'forms': form,'form_image': form_image})

#                         # if cd['code'] != '':
#                         #     print('shet')
#                         #     if str(code) == str(cd['code']):
#                         #         print('shetttt')


#
#
#                         # return render(request, 'Migration/forms/signin.html',
#                         #               {'save_user': save_user, 'forms': form, 'account': account})

                    # if str(code)==str(cd['code']):
                    #     user.save()
                    #     account.save()
                    #     save_user = True
                    #     user = authenticate(request, username=cd["user_name"], password=cd["password"])
                    #
                    #     if user is not None:
                    #         login(request, user)
                    #
                    #     return render(request, 'Migration/forms/signin.html', {'save_user': save_user, 'forms': form})
                    # else:
                    #     messages.error(request, "کد تایید نادرست است")  # ایجاد پیام موفقیت
                    #     return render(request, 'Migration/post/home.html', {'save_user': save_user, 'forms': form})

                else:
                    not_correct_password = True
                    return render(request, 'Migration/forms/signin.html',
                    {'save_user': save_user, "not_correct_password": not_correct_password, 'forms': form,'form_image': form_image})
                # else:
                #     return render(request, 'Migration/forms/signin.html', {"forms": form})
            else:
                return render(request, 'Migration/forms/signin.html', {"forms": form,'form_image': form_image})

        else:
            # global send_code
            # if send_code:
            #     import random
            #     code = random.randint(100000, 999999)
            #
            form = signin_form()
            print("get")
            return render(request, 'Migration/forms/signin.html', {"forms": form,'form_image': form_image})
    else:
        return redirect("my_site:consulting")


def view_login(request):
    print('log-')
    global save_user,form_image
    if request.method == "POST":
        form = login_form(request.POST)
        if form.is_valid():
            print('log-valid')
            cd = form.cleaned_data
            # from django.db.models import Q
            #
            # if signin_model.objects.filter(Q(user_name=cd['user_name']) & Q(password=cd['password'])).exists():
            #     print('open')
            user = authenticate(request, username=cd["user_name"], password=cd["password"])

my_site/templates/Migration/parent/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" >

    <link rel="stylesheet" type="text/css" href="{% static "css/header.css" %}" >
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>

    <meta charset="UTF-8">
<title>{% block title %}Title{% endblock %}</title>
    {% block head %}{% endblock %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<body>
{% include 'Migration/partials/header.html' %}
{% include 'Migration/partials/navigation.html' %}

{% if form_image.instance.photo and save_user %}

    <img src="{{ form_image.instance.photo.url }}" alt="User Photo" style="border-radius: 1000px;width: 90px;height: 90px">
{% endif %}

<a href="{% url 'my_site:consulting' %}">
    <img src="{% static 'images/headphone-help.jpg' %}" alt="" id="council">
    </a>

{#این کد برای پیام هاست.پیام های جنگو#}
    {% if messages %}
    <ul  style="text-align: right;margin-top:10px">
        {% for message in messages %}
            <li class="messages">{{ message }}</li>

        {% endfor %}
    </ul>
            <button id="clearMessagesButton" style=";border:none;width: 15%;border-radius: 20px;background-color: #f39c12;color: white;padding: 10px">پیام پاک کن</button>

    {% endif %}

<br><br>

{% if not save_user %}
    <a href="{% url 'my_site:signin' %}">
    <button type="button" class="sign-button" >اول<br> ثبت نام<br> کن
    </button></a>
    <a href="{% url 'my_site:login' %}">
    <button type="button"  class="sign-button login-button" >وارد شو
    </button></a>
{% else %}
    <a href="{% url 'my_site:logout' %}">
        <button type="button" class="sign-button logout-button" >به سلامت
        </button></a>
    <a href="{% url 'my_site:profile' %}">
        <button type="button" class="sign-button profile-button" >پروفایلت
        </button></a>

{% endif %}
    <div class="god">
<div class="parent_div">
    <div style="color: red">
    {% if forms.errors %}
{#            لطفا خطاهای زیر را اصلاح کنید:#}
        <br> <br>
        {% for field in forms %}
            {% if field.errors %}
                {% for error in field.errors %}
{#                    {{ field.label }}:#}
                    *{{ error }}
                    <br>
                {% endfor %}
            {% endif %}
        {% endfor %}

        {% if forms.non_field_errors %}
            {{ forms.non_field_errors }}
            <br>
    {% endif %}

    {% endif %}
</div>


{% block content %}
{% endblock %}

</div>
    </div>
<button onclick="scrollToTop()" id="go-top-button">برو بالا</button>
{% include 'Migration/partials/footer.html' %}

</body>
<script>
function scrollToTop() {
    window.scrollTo({ top: 0, behavior: 'smooth' });
}

$(document).ready(function() {
    $("#clearMessagesButton").click(function() {
        $(".messages").remove();
        $("#clearMessagesButton").remove();
    });
});
</script>

</html>