Migration/urls.py
from django.contrib import admin
from django.urls import path,include
from django_telethon.urls import django_telethon_urls

admin.autodiscover()
from django.conf.urls.static import static
from django.conf import settings


#
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('home/',include('my_site.urls',namespace='my_site')),
#     path('telegram/', django_telethon_urls()),
# ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('my_site.urls',namespace='my_site')),
    path('telegram/', django_telethon_urls()),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/urls.py
from django.conf.urls.static import static
from django.urls import path

from Migration import settings
from . import views
app_name = 'my_site'

urlpatterns=[
    path('home/',views.home, name='home'),
    path('work/', views.work, name='work'),
    path('study/',views.study,name='study'),
    path('life/', views.life, name='life'),
    path('consulting/',views.consulting, name='consulting'),
    path('signin/', views.signin, name='signin'),
    path('login/', views.view_login, name='login'),
    path('vissa/', views.vissa, name='vissa'),
    path('usa/', views.usa, name='usa'),
    path('germany/', views.germany, name='germany'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('look_profile/', views.look_profile, name='look_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('suggestion/', views.suggestion, name='suggestion'),
    path('Verification_code/', views.Verification_code_view, name='Verification_code'),
    path('iamge/', views.upload_photo, name='upload_photo'),
    path('reset-password/', views.reset_password_view, name='reset_password'),
    # path('iamge/', views.model_form_upload, name='upload_photo'),

]

my_site/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render, reverse


class signin_model(models.Model):
    user_name = models.CharField(max_length=20)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    mobile = models.CharField(max_length=11)
    users = models.OneToOneField(User, on_delete=models.CASCADE, related_name='account')
    photo = models.ImageField(upload_to='photos/')

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class UserProfile(models.Model):
    photo = models.ImageField(upload_to='photos/')


# class Document(models.Model):
#     # document_addr = models.FileField(upload_to='documents/')
#     # uploaded_at = models.DateTimeField(auto_now_add=True)
#     document_addr = models.FileField(upload_to='documents/%Y/%m/%d/')

my_site/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth.models import User
from .models import signin_model
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from datetime import date, datetime
from khayyam import JalaliDate, JalaliDatetime, TehranTimezone
import csv
from datetime import date
import random

save_user = False
form_image=False

def home(request):

    return render(request, 'Migration/post/home.html', {'save_user': save_user,'form_image':form_image})


def work(request):
    return render(request, 'Migration/post/work.html', {'save_user': save_user,'form_image':form_image})


def study(request):
    return render(request, 'Migration/post/study.html', {'save_user': save_user,'form_image':form_image})


def life(request):
    return render(request, 'Migration/post/life.html', {'save_user': save_user,'form_image': form_image})


def vissa(request):
    return render(request, 'Migration/post/vissa.html', {'save_user': save_user,'form_image': form_image})


def usa(request):
    return render(request, 'Migration/post/countries/usa.html', {'save_user': save_user,'form_image': form_image})


def germany(request):
    return render(request, 'Migration/post/countries/germany.html', {'save_user': save_user,'form_image': form_image})


def about(request):

    return render(request, 'Migration/post/about.html', {'save_user': save_user,'form_image': form_image})


def feedback(request):
    sent = False
    if request.method == "POST":
        form = feedback_form(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = cd['name']
            emails = cd['email']
            subject = cd['subject']
            message = cd['message']
            phone = cd['phone']
            msg = "name:{0}\nphone:{1}\nemail:{2}\nmessage:\n{3}".format(name, phone, emails, message)
            send_mail(subject, msg, 'lopmotop@gmail.com', ['lopmotop@gmail.com'], fail_silently=False)
            sent = True
    else:
        form = feedback_form()

    return render(request, 'Migration/post/feedback.html', {'save_user': save_user, 'forms': form,'form_image': form_image})


def consulting(request):
    if not save_user:
        return redirect("my_site:signin")
    print('consulting')

    my_range = range(1, 100)
    context = {
        'my_range': my_range
    }

    sent = False
    if request.method == "POST":
        print('e-post')
        form = email_consulting(request.POST)
        if form.is_valid():
            print('e-valid')

            cd = form.cleaned_data
            name = cd['name']
            type_consulting = cd['type_consulting']
            level_school = cd['level_school']
            type = cd['type']
            age = cd['age']
            type_price = cd['type_price']
            mobile = cd['mobile']
            city = cd['city']

            msg = ("name: {0}\nphone: {1}\ncity: {2}\ntype_consulting: {3}"
                   "\nlevel_school: {4}\ntype: {5}"
                   "\ntype_price: {6}\nage {7}").format(
                name, mobile, city, type_consulting, level_school, type, type_price, age)

            send_mail("فرم مشاوره", msg, 'lopmotop@gmail.com',
                      ['lopmotop@gmail.com'], fail_silently=False)
            sent = True
    else:
        print('e-get')

    form = email_consulting()
    return render(request, 'Migration/post/consulting.html',
                  {'save_user': save_user, 'sent': sent, "context": context,'form_image': form_image})


# send_code = 0

code = 0


def Verification_code_view(request):
    # global code
    # import random
    # code = random.randint(100000, 999999)
    # print(code)
    # global send_code
    # import random
    # code = random.randint(100000, 999999)
    # print(code)
    # form=signin_form(request.POST)
    # if form.is_valid():
    #     email=form.cleaned_data['email']
    #     print(email)
    # send_code = True
    # return redirect('my_site:signin')
    return render(request, 'Migration/forms/signin.html')


def signin(request):
    # return render(request,'Migration/post/home.html')
    print('yes')
    global code
    global save_user
    if not save_user:
        print('NO save')
        # user = request.user
        # try:
        #     account = signin_model.objects.get(users=user)
        #
        # except:
        #
        if request.method == "POST":
            form = signin_form(request.POST)
            print('post')
            if form.is_valid():
                print('valid-post')
                cd = form.cleaned_data
                if cd['repassword'] == cd["password"]:

                    if cd['code'] == '':
                        print('shet')
                        import random
                        code = random.randint(100000, 999999)
                        print(code)
                        dict_form= [cd['user_name'], cd['first_name'], cd['last_name'], cd['password'], cd['repassword'],
                                    cd['email'], cd['mobile']]

                        send_mail('کد تایید', 'کد تایید شما برای ثبت نام در سایت مهاجر\n' + str(code),
                                  'lopmotop@gmail.com',
                                  [cd['email']],
                                  fail_silently=False)

                        return render(request,'Migration/forms/signin.html',{'form':form,'dict_form':dict_form})
                    else:
                        print("code", code)
                        if str(code) == str(cd['code']):

                            user = User.objects.create_user(cd["user_name"], cd["email"], cd["password"])
                            user.first_name = cd["first_name"]
                            user.last_name = cd["last_name"]
                            account = signin_model.objects.create(users=user)
                            user.first_name = cd['first_name']
                            user.last_name = cd['last_name']
                            account.first_name = cd['first_name']
                            account.last_name = cd['last_name']
                            account.password = cd['password']
                            account.email = cd['email']
                            account.mobile = cd['mobile']
                            account.user_name = cd['user_name']
                            user.save()
                            account.save()
                            save_user = True
                            user = authenticate(request, username=cd["user_name"], password=cd["password"])
                            if user is not None:
                                login(request, user)
                                messages.success(request, "خوش اومدی")  # ایجاد پیام موفقیت
                                return render(request, 'Migration/post/home.html',{'save_user': save_user, 'forms': form,'form_image': form_image})
                        else:
                            messages.error(request, "کد تایید نادرست است")  # ایجاد پیام موفقیت
                            return render(request, 'Migration/post/home.html', {'save_user': save_user, 'forms': form,'form_image': form_image})

#                         # if cd['code'] != '':
#                         #     print('shet')
#                         #     if str(code) == str(cd['code']):
#                         #         print('shetttt')


#
#
#                         # return render(request, 'Migration/forms/signin.html',
#                         #               {'save_user': save_user, 'forms': form, 'account': account})

                    # if str(code)==str(cd['code']):
                    #     user.save()
                    #     account.save()
                    #     save_user = True
                    #     user = authenticate(request, username=cd["user_name"], password=cd["password"])
                    #
                    #     if user is not None:
                    #         login(request, user)
                    #
                    #     return render(request, 'Migration/forms/signin.html', {'save_user': save_user, 'forms': form})
                    # else:
                    #     messages.error(request, "کد تایید نادرست است")  # ایجاد پیام موفقیت
                    #     return render(request, 'Migration/post/home.html', {'save_user': save_user, 'forms': form})

                else:
                    not_correct_password = True
                    return render(request, 'Migration/forms/signin.html',
                    {'save_user': save_user, "not_correct_password": not_correct_password, 'forms': form,'form_image': form_image})
                # else:
                #     return render(request, 'Migration/forms/signin.html', {"forms": form})
            else:
                return render(request, 'Migration/forms/signin.html', {"forms": form,'form_image': form_image})

        else:
            # global send_code
            # if send_code:
            #     import random
            #     code = random.randint(100000, 999999)
            #
            form = signin_form()
            print("get")
            return render(request, 'Migration/forms/signin.html', {"forms": form,'form_image': form_image})
    else:
        return redirect("my_site:consulting")


def view_login(request):
    print('log-')
    global save_user,form_image
    if request.method == "POST":
        form = login_form(request.POST)
        if form.is_valid():
            print('log-valid')
            cd = form.cleaned_data
            # from django.db.models import Q
            #
            # if signin_model.objects.filter(Q(user_name=cd['user_name']) & Q(password=cd['password'])).exists():
            #     print('open')
            user = authenticate(request, username=cd["user_name"], password=cd["password"])

my_site/templates/Migration/forms/image_profile.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
 <link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}" >
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock %}
{% block content %}

<h1>Upload Your Photo</h1>
<form method="post" enctype="multipart/form-data">
    <h2>یه عکس انتخاب کن</h2>
    {% csrf_token %}
    <input type="file" name="photo">
    <input type="submit">
</form>
{#{% if post == True %}#}
{#{% if form_image.instance.photo %}#}
{#    <h2>Your Photo:</h2>#}
{#    <img src="{{ form_image.instance.photo.url }}" alt="User Photo" style="border-radius: 1000px;width: 90px;height: 90px">#}
{#{% endif %}#}
{#{% endif %}#}
{% endblock %}

{#{% extends 'base.html' %}#}
{##}
{#{% block content %}#}
{#  <form method="post" enctype="multipart/form-data">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button type="submit">Upload</button>#}
{#  </form>#}
{##}
{#  <p><a href="{% url 'my_site:home' %}">Return to home</a></p>#}
{##}
{#    <img src="{{ MEDIA_URL}}{{document.document_addr }}">#}
{##}
{#{% endblock %}#}

my_site/templates/Migration/forms/login.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
        <link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}" >

{% endblock %}
{% block content %}

   <form action="#" method="post">
   {% csrf_token %}
        <p style="color: white;text-align: center"> <b> ورود</b></p>
        <p class="p-2">نام کاربری</p>
      <i class="fa fa-user user"></i>  <input type="text" name="user_name" placeholder= "نام کاربری را وارد کنید" >

      <p class="p-2">کلمه عبور</p>
       <i class="fa fa-lock user"></i> <input type="password" name="password" placeholder="کلمه عبور را وارد کنید">
        <a href="{% url 'my_site:reset_password' %}" class="p-2" style="text-align: right">فراموشی کلمه عبور؟</a>

        <input type="submit" value="ورود">



          <i class="fa fa-google  g"></i>
        <i class="fa fa-twitter  t"></i>
        <i class="fa fa-facebook-f  f"></i>

        <br><br>
         <a class="p-6" href="#">ثبت نام</a>
    </form>
{% endblock %}

my_site/templates/Migration/forms/reset_password.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
        <link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}" >
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

{% endblock %}
{% block content %}
    <script src="{% static 'javascript/timer_reset_code.js' %}"></script>

    <form method="post">
        {% csrf_token %}
        <p style="color: white;text-align: center"> <b> بازیابی رمز</b></p>
        <p class="p-2">ایمیل</p>
        <i class="fa fa-google google"></i>
        <input {% if email %} value="{{ email | default:'' }}" {% endif %}  type="text" name="email" placeholder= "ایمیل را وارد کنید">

        <br><br><br>
        {#       <a href="{% url 'my_site:Verification_code' %}" >#}
        <input {% if disable_send_code %}disabled {% endif %} type="submit" value="ارسال کد تایید"
               id="Verification_button"  name="send_code">
        {#           </a>#}
        <input type="number" id="Verification_input" name="code" >

        <input type="submit" value="ثبت" name="sub">
{#        {% if js_time %}#}
            <h5 style="color: white" id="timer">00:00</h5>
{#        {% else %}#}

{#        {% endif %}#}
        <br><br>
        <a class="p-6" href="{% url 'my_site:signin' %}">ثبت نام</a>
    </form>
{% endblock %}

my_site/templates/Migration/forms/signin.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
        <link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}" >

{% endblock %}
{% block content %}
{#    {% if messages %}#}
{#    <ul class="messages" style="text-align: right">#}
{#        {% for message in messages %}#}
{#            <li>{{ message }}</li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% endif %}#}

   <form action="#" method="post">
        {% csrf_token %}
        <p style="color: white" class="p-1"> <b>ثبت نام</b></p>
   {% if not_correct_password %}
       <h5 style="color: #f39c12;text-align: right">پسوورد با تکرار آن برابر نیست</h5>
   {% endif %}

        <p class="p-2">نام کاربری</p>
        <i class="fa fa-user user"></i>  <input {% if forms.user_name.value %} value="{{ forms.user_name.value }}" {% else %}value="{{ dict_form.0 | default:'' }}"{% endif %}
       type="text" name="user_name" placeholder= "نام کاربری خودرا وارد کنید" >
        <p class="p-2">نام</p>
        <i class="fa fa-user user"></i>  <input {% if forms.first_name.value %} value="{{ forms.first_name.value }}"  {% else %}value="{{ dict_form.1 | default:'' }}" {% endif %} type="text" name="first_name" placeholder= "نام خودرا را وارد کنید" >
        <p class="p-2">نام خانوادگی</p>
        <i class="fa fa-user user"></i>   <input {% if forms.last_name.value %} value="{{ forms.last_name.value }}"  {% else %}value="{{ dict_form.2 | default:'' }}"{% endif %} type="text" name="last_name" placeholder= "نام خانوادگی خودرا وارد کنید" >

       <p class="p-2">پسوورد</p>
       <i class="fa fa-lock lock"></i> <input {% if forms.password_name.value %} value="{{ forms.password_name.value }}"  {% else %}value="{{ dict_form.3 | default:'' }}" {% endif %} type="password" name="password" placeholder="پسوورد خود را وارد کنید">
       <p class="p-2">تکرار پسوورد</p>
       <i class="fa fa-lock lock"></i> <input {% if forms.repassword.value %} value="{{ forms.repassword.value }}"  {% else %}value="{{ dict_form.4 | default:'' }}" {% endif %} type="password" name="repassword" placeholder="تکرار پسوورد را وارد کنید">


       <p class="p-2">ایمیل</p>
       <i class="fa fa-google google"></i> <input {% if forms.email.value %} value="{{ forms.email.value }}"  {% else %}value="{{ dict_form.5 | default:'' }}" {% endif %} type="email" name="email" placeholder="ایمیل خودرا را وارد کنید">
       <p class="p-2">شماره موبایل</p>
       <i class="fa fa-phone phone" ></i> <input {% if forms.mobile.value %} value="{{ forms.mobile.value }}"  {% else %}value="{{ dict_form.6 | default:'' }}" {% endif %} type="number" name="mobile" placeholder="شماره موبایل را وارد کنید">
       <br><br><br>
       <a href="{% url 'my_site:Verification_code' %}" ><input type="submit" value="ارسال کد تایید"
                 id="Verification_button" ></a>
        <input type="number" id="Verification_input" name="code" >



        <input type="submit" value="ثبت نام">



          <i class="fa fa-google  g"></i>
        <i class="fa fa-twitter  t"></i>
        <i class="fa fa-facebook-f  f"></i>

         <p class="p-3 p-1">برای استفاده ثبت نام کنید</p>
             </form>
{% endblock %}

my_site/templates/Migration/forms/suggestion.html
{% extends "Migration/parent/base.html" %}
{% load static %}
{% block title %}mohajer{% endblock %}
{% block head %}
{#        <link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}" >#}
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

{% endblock %}
{% block content %}

{#این کد برای پیام هاست.پیام های جنگو#}
{#    {% if messages %}#}
{#    <ul class="messages" style="text-align: right">#}
{#        {% for message in messages %}#}
{#            <li>{{ message }}</li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% endif %}#}
{##}

    <form method="post" style="text-align: right;background-color: #cccccc;border-radius: 15px;width: 40%;padding: 15px">
        {% csrf_token %}
        <label>نام:
            <input type="text" name="name">
        </label>
        <br>
        <label>نظرت:
<textarea  value="نظر خود را اینجا بنویسید" name="suggest" style="resize: none;max-width: 300px;max-height: 300px;">
</textarea>
        </label>
        <br>

        <label>

    <input type="submit" value="ارسال" style="background-color: #166e6b;color: white;padding: 10px;border: 2px solid #09524f;border-radius: 15px">

        </label>    </form>
<br><br><br><br>
        {% for account in dt %}
    <div style="margin-bottom: 40px;text-align: right;background-color: #cccccc;padding: 30px;border-radius:15px;width: 40%  ">
    <div>

           <span style="font-size:15px;">{{ account.0|default:'' }}</span>
            <br><br>
            <h5>{{ account.1 |default:''}}</h5>
            <p>{{ account.2 |default:'' }}</p>
    </div>
    </div>

        {% endfor %}
{% endblock %}
{#{% include "shared/messages.html" %}#}